### ISSUE TITLE
RUN Instructions

### ISSUE THREAD

**Issue by ishandutta04** [stevinz/extrude#3]
Hi,

Can you please include the run instructions for the project for a sample image in the README file?

**Comment by stevinz** [comment]
There is an example project included in the repository. It has been tested using VSCode + CMake on an Intel Mac, Apple Silicon Mac, and HTML (using WASM). Also using Visual Studio 2017 & 2019 + CMake on Windows 10.

To run the example in VSCode (with CMake extension installed), download and extract the repository and open the extracted folder in VSCode. Then under the CMake extension, select 'Build All Projects'.  The example uses ImGui for windowing and input; Sokol for file handling and rendering (necessary shaders for Sokol have already been pre-compiled for all platforms). A standalone binary will be created in the 'build' directory.

...

Beyond that, you should be able to look through the example (located in 'example/main.cpp') to see the basics of how the library works. In the init() function you will see the image "/assets/shapes.png" is selected as the initial image and later loaded by Sokol in the load_image() function (once fetched). After the image is loaded, the function calculateMesh() shows the process of creating geometry. The heart of the library is the extrudeObjectFromPolygon() function located in 'src/mesh_extrude.cpp'.

In the example (example/main.cpp, line 309):
```
DrMesh mesh {};
mesh.extrudeObjectFromPolygon(&image, object, mesh_quality, (float)(image_size) * depth_multiplier);
```

Function definition in the library (src/mesh_extrude.cpp):
```
void DrMesh::extrudeObjectFromPolygon(image, poly_number, quality, depth_multiplier) {
```

...

Sorry to say, but I don't have more time for help using the library. I haven't messed with it in a while, it was created and released open source for creative / demonstration purposes, not really as a production ready library.

For a more complete, stable, production ready example of extrusion, I recommend checking out the [ExtrudeGeometry](https://threejs.org/docs/index.html?q=extrud#api/en/geometries/ExtrudeGeometry) class of the Javascript library [Three.js](https://github.com/mrdoob/three.js/). They have [several examples](https://threejs.org/examples/?q=extrude) and many other examples can be found online; like [this example of extruding an image using SVGLoader](https://stackoverflow.com/questions/56023033/three-js-how-to-extrude-a-shape-defined-by-an-image-file).

For a more complete C/C++ solution, I recommend checking out the blog post [Marching Squares](https://prideout.net/marching-squares). Source code can be found on github ([par_msquares.h](https://github.com/prideout/par/blob/master/par_msquares.h)).
